// Mocks generated by Mockito 5.4.6 from annotations
// in local_ai_chat/test/features/chat/domain/repositories/chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:local_ai_chat/features/chat/domain/entities/session_entity.dart'
    as _i4;
import 'package:local_ai_chat/features/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> loadModel(String? modelPath) =>
      (super.noSuchMethod(
            Invocation.method(#loadModel, [modelPath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<String> sendMessageStream(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageStream, [text]),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Future<List<_i4.SessionEntity>> getSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, []),
            returnValue: _i3.Future<List<_i4.SessionEntity>>.value(
              <_i4.SessionEntity>[],
            ),
          )
          as _i3.Future<List<_i4.SessionEntity>>);

  @override
  _i3.Future<List<_i4.MessageEntity>> getMessages(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [sessionId]),
            returnValue: _i3.Future<List<_i4.MessageEntity>>.value(
              <_i4.MessageEntity>[],
            ),
          )
          as _i3.Future<List<_i4.MessageEntity>>);

  @override
  _i3.Future<void> saveMessage(String? sessionId, _i4.MessageEntity? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [sessionId, message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createSession(_i4.SessionEntity? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
