// Mocks generated by Mockito 5.4.6 from annotations
// in local_ai_chat/test/features/chat/data/datasources/llama_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:llamadart/src/backends/backend.dart' as _i2;
import 'package:llamadart/src/core/engine/chat_session.dart' as _i15;
import 'package:llamadart/src/core/engine/engine.dart' as _i4;
import 'package:llamadart/src/core/models/chat/chat_message.dart' as _i9;
import 'package:llamadart/src/core/models/chat/chat_template_result.dart'
    as _i3;
import 'package:llamadart/src/core/models/chat/completion_chunk.dart' as _i8;
import 'package:llamadart/src/core/models/chat/content_part.dart' as _i13;
import 'package:llamadart/src/core/models/config/log_level.dart' as _i5;
import 'package:llamadart/src/core/models/inference/generation_params.dart'
    as _i10;
import 'package:llamadart/src/core/models/inference/model_params.dart' as _i7;
import 'package:llamadart/src/core/models/inference/tool_choice.dart' as _i12;
import 'package:llamadart/src/core/models/tools/tool_definition.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLlamaBackend_0 extends _i1.SmartFake implements _i2.LlamaBackend {
  _FakeLlamaBackend_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlamaChatTemplateResult_1 extends _i1.SmartFake
    implements _i3.LlamaChatTemplateResult {
  _FakeLlamaChatTemplateResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlamaEngine_2 extends _i1.SmartFake implements _i4.LlamaEngine {
  _FakeLlamaEngine_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LlamaEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlamaEngine extends _i1.Mock implements _i4.LlamaEngine {
  MockLlamaEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LlamaBackend get backend =>
      (super.noSuchMethod(
            Invocation.getter(#backend),
            returnValue: _FakeLlamaBackend_0(this, Invocation.getter(#backend)),
          )
          as _i2.LlamaBackend);

  @override
  _i5.LlamaLogLevel get dartLogLevel =>
      (super.noSuchMethod(
            Invocation.getter(#dartLogLevel),
            returnValue: _i5.LlamaLogLevel.none,
          )
          as _i5.LlamaLogLevel);

  @override
  _i5.LlamaLogLevel get nativeLogLevel =>
      (super.noSuchMethod(
            Invocation.getter(#nativeLogLevel),
            returnValue: _i5.LlamaLogLevel.none,
          )
          as _i5.LlamaLogLevel);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> get supportsVision =>
      (super.noSuchMethod(
            Invocation.getter(#supportsVision),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> get supportsAudio =>
      (super.noSuchMethod(
            Invocation.getter(#supportsAudio),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> setLogLevel(_i5.LlamaLogLevel? level) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [level]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setDartLogLevel(_i5.LlamaLogLevel? level) =>
      (super.noSuchMethod(
            Invocation.method(#setDartLogLevel, [level]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setNativeLogLevel(_i5.LlamaLogLevel? level) =>
      (super.noSuchMethod(
            Invocation.method(#setNativeLogLevel, [level]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadModel(
    String? path, {
    _i7.ModelParams? modelParams = const _i7.ModelParams(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadModel, [path], {#modelParams: modelParams}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadModelFromUrl(
    String? url, {
    _i7.ModelParams? modelParams = const _i7.ModelParams(),
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadModelFromUrl,
              [url],
              {#modelParams: modelParams, #onProgress: onProgress},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadMultimodalProjector(String? mmProjPath) =>
      (super.noSuchMethod(
            Invocation.method(#loadMultimodalProjector, [mmProjPath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unloadMultimodalProjector() =>
      (super.noSuchMethod(
            Invocation.method(#unloadMultimodalProjector, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unloadModel() =>
      (super.noSuchMethod(
            Invocation.method(#unloadModel, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i8.LlamaCompletionChunk> create(
    List<_i9.LlamaChatMessage>? messages, {
    _i10.GenerationParams? params,
    List<_i11.ToolDefinition>? tools,
    _i12.ToolChoice? toolChoice,
    bool? parallelToolCalls = false,
    bool? enableThinking = true,
    String? sourceLangCode,
    String? targetLangCode,
    Map<String, dynamic>? chatTemplateKwargs,
    DateTime? templateNow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #create,
              [messages],
              {
                #params: params,
                #tools: tools,
                #toolChoice: toolChoice,
                #parallelToolCalls: parallelToolCalls,
                #enableThinking: enableThinking,
                #sourceLangCode: sourceLangCode,
                #targetLangCode: targetLangCode,
                #chatTemplateKwargs: chatTemplateKwargs,
                #templateNow: templateNow,
              },
            ),
            returnValue: _i6.Stream<_i8.LlamaCompletionChunk>.empty(),
          )
          as _i6.Stream<_i8.LlamaCompletionChunk>);

  @override
  _i6.Future<_i3.LlamaChatTemplateResult> chatTemplate(
    List<_i9.LlamaChatMessage>? messages, {
    bool? addAssistant = true,
    Map<String, dynamic>? jsonSchema,
    List<_i11.ToolDefinition>? tools,
    _i12.ToolChoice? toolChoice = _i12.ToolChoice.auto,
    bool? parallelToolCalls = false,
    bool? enableThinking = true,
    Map<String, dynamic>? responseFormat,
    String? customTemplate,
    String? sourceLangCode,
    String? targetLangCode,
    bool? includeTokenCount = true,
    Map<String, dynamic>? chatTemplateKwargs,
    DateTime? templateNow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #chatTemplate,
              [messages],
              {
                #addAssistant: addAssistant,
                #jsonSchema: jsonSchema,
                #tools: tools,
                #toolChoice: toolChoice,
                #parallelToolCalls: parallelToolCalls,
                #enableThinking: enableThinking,
                #responseFormat: responseFormat,
                #customTemplate: customTemplate,
                #sourceLangCode: sourceLangCode,
                #targetLangCode: targetLangCode,
                #includeTokenCount: includeTokenCount,
                #chatTemplateKwargs: chatTemplateKwargs,
                #templateNow: templateNow,
              },
            ),
            returnValue: _i6.Future<_i3.LlamaChatTemplateResult>.value(
              _FakeLlamaChatTemplateResult_1(
                this,
                Invocation.method(
                  #chatTemplate,
                  [messages],
                  {
                    #addAssistant: addAssistant,
                    #jsonSchema: jsonSchema,
                    #tools: tools,
                    #toolChoice: toolChoice,
                    #parallelToolCalls: parallelToolCalls,
                    #enableThinking: enableThinking,
                    #responseFormat: responseFormat,
                    #customTemplate: customTemplate,
                    #sourceLangCode: sourceLangCode,
                    #targetLangCode: targetLangCode,
                    #includeTokenCount: includeTokenCount,
                    #chatTemplateKwargs: chatTemplateKwargs,
                    #templateNow: templateNow,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.LlamaChatTemplateResult>);

  @override
  _i6.Stream<String> generate(
    String? prompt, {
    _i10.GenerationParams? params = const _i10.GenerationParams(),
    List<_i13.LlamaContentPart>? parts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generate,
              [prompt],
              {#params: params, #parts: parts},
            ),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  void cancelGeneration() => super.noSuchMethod(
    Invocation.method(#cancelGeneration, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<List<int>> tokenize(String? text, {bool? addSpecial = true}) =>
      (super.noSuchMethod(
            Invocation.method(#tokenize, [text], {#addSpecial: addSpecial}),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<String> detokenize(List<int>? tokens, {bool? special = false}) =>
      (super.noSuchMethod(
            Invocation.method(#detokenize, [tokens], {#special: special}),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#detokenize, [tokens], {#special: special}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<int> getTokenCount(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#getTokenCount, [text]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<double>> embed(String? text, {bool? normalize = true}) =>
      (super.noSuchMethod(
            Invocation.method(#embed, [text], {#normalize: normalize}),
            returnValue: _i6.Future<List<double>>.value(<double>[]),
          )
          as _i6.Future<List<double>>);

  @override
  _i6.Future<List<List<double>>> embedBatch(
    List<String>? texts, {
    bool? normalize = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#embedBatch, [texts], {#normalize: normalize}),
            returnValue: _i6.Future<List<List<double>>>.value(<List<double>>[]),
          )
          as _i6.Future<List<List<double>>>);

  @override
  _i6.Future<Map<String, String>> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<int> getContextSize() =>
      (super.noSuchMethod(
            Invocation.method(#getContextSize, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> setLora(String? path, {double? scale = 1.0}) =>
      (super.noSuchMethod(
            Invocation.method(#setLora, [path], {#scale: scale}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeLora(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#removeLora, [path]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearLoras() =>
      (super.noSuchMethod(
            Invocation.method(#clearLoras, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> getBackendName() =>
      (super.noSuchMethod(
            Invocation.method(#getBackendName, []),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getBackendName, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> getAvailableBackends() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBackends, []),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getAvailableBackends, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<int?> getResolvedGpuLayers() =>
      (super.noSuchMethod(
            Invocation.method(#getResolvedGpuLayers, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<_i2.BackendPerfContextData?> getPerformanceContext() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceContext, []),
            returnValue: _i6.Future<_i2.BackendPerfContextData?>.value(),
          )
          as _i6.Future<_i2.BackendPerfContextData?>);

  @override
  _i6.Future<bool> isGpuSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isGpuSupported, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<({int free, int total})> getVramInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getVramInfo, []),
            returnValue: _i6.Future<({int free, int total})>.value((
              free: 0,
              total: 0,
            )),
          )
          as _i6.Future<({int free, int total})>);
}

/// A class which mocks [ChatSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSession extends _i1.Mock implements _i15.ChatSession {
  MockChatSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LlamaEngine get engine =>
      (super.noSuchMethod(
            Invocation.getter(#engine),
            returnValue: _FakeLlamaEngine_2(this, Invocation.getter(#engine)),
          )
          as _i4.LlamaEngine);

  @override
  List<_i9.LlamaChatMessage> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <_i9.LlamaChatMessage>[],
          )
          as List<_i9.LlamaChatMessage>);

  @override
  set maxContextTokens(int? value) => super.noSuchMethod(
    Invocation.setter(#maxContextTokens, value),
    returnValueForMissingStub: null,
  );

  @override
  set systemPrompt(String? value) => super.noSuchMethod(
    Invocation.setter(#systemPrompt, value),
    returnValueForMissingStub: null,
  );

  @override
  void addMessage(_i9.LlamaChatMessage? message) => super.noSuchMethod(
    Invocation.method(#addMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void reset({bool? keepSystemPrompt = true}) => super.noSuchMethod(
    Invocation.method(#reset, [], {#keepSystemPrompt: keepSystemPrompt}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<_i8.LlamaCompletionChunk> create(
    List<_i13.LlamaContentPart>? parts, {
    _i10.GenerationParams? params,
    List<_i11.ToolDefinition>? tools,
    _i12.ToolChoice? toolChoice,
    bool? parallelToolCalls = false,
    bool? enableThinking = true,
    Map<String, dynamic>? chatTemplateKwargs,
    void Function(_i9.LlamaChatMessage)? onMessageAdded,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #create,
              [parts],
              {
                #params: params,
                #tools: tools,
                #toolChoice: toolChoice,
                #parallelToolCalls: parallelToolCalls,
                #enableThinking: enableThinking,
                #chatTemplateKwargs: chatTemplateKwargs,
                #onMessageAdded: onMessageAdded,
              },
            ),
            returnValue: _i6.Stream<_i8.LlamaCompletionChunk>.empty(),
          )
          as _i6.Stream<_i8.LlamaCompletionChunk>);
}
